# makefile
all:	        filegrep.o lsal.o lsal2.o
filegrep.o:	filegrep.c
	        gcc filegrep.c -o filegrep.o
lsal.o:         lsal.c
	        gcc lsal.c -o lsal.o
lsal2.o:        lsal2.c
	        gcc lsal2.c -o lsal2.o